Implemente em python o algoritmo Needleman Wunsch para alinhamento de cadeias. 
Faça em jupyter e coloque exemplos de cadeias como experimentos e seus resultados.

In [9]:
import numpy as np

def Wunsch(x , y):
    
    #concatena cerquilha as duas strings
    cadeiax = "#" + x 
    cadeiay = "#" + y
    
    m = len(cadeiax)
    n = len(cadeiay)
    
    #criando matriz de tamanho m linhas e n colunas
    matrix = [[[] for j in range(n)] for i in range(m)]
       
    #inicializando linha 
    matrix[0] = [-j for j in range(n)]

    for i in range(1,m):
        matrix[i][0] = -i
    
    s = 0
    
    for i in range(1,m):
        for j in range(1,n):
            if cadeiax[i] == cadeiay[j]:
                s = 1
            else:
                s = -1
            
            matrix[i][j] = max(matrix[i-1][j-1]+s,matrix[i][j-1]-1,matrix[i-1][j]-1)
    print(np.asmatrix(matrix))
    
    return matrix[m-1][n-1]
    

In [10]:
Wunsch("atcat","attatc")

[[ 0 -1 -2 -3 -4 -5 -6]
 [-1  1  0 -1 -2 -3 -4]
 [-2  0  2  1  0 -1 -2]
 [-3 -1  1  1  0 -1  0]
 [-4 -2  0  0  2  1  0]
 [-5 -3 -1  1  1  3  2]]


2